### ISSUE TITLE
Tests for `git show **` are failing in Arch Linux

### ISSUE THREAD

**Issue by chitoku-k** [chitoku-k/fzf-zsh-completions#105]
## Environment
OS: Arch Linux
git version 2.30.2
zsh 5.8 (x86_64-pc-linux-gnu)

## Failing Tests
The ones that satisfy the following conditions are failing in specific environments:
- completions for `git show`
- completes by calling `git show --pretty=format: --name-only -z $treeish`

https://github.com/chitoku-k/fzf-zsh-completions/blob/5c41f3bd8b684df4677db8516e64dc745be09412/tests/git.zunit#L4369-L4398
https://github.com/chitoku-k/fzf-zsh-completions/blob/5c41f3bd8b684df4677db8516e64dc745be09412/tests/git.zunit#L4432-L4463

**Comment by hexium310** [comment]
It seems that the behaviour `o` parameter expansion flag in Zsh differ by OSes. In Arch Linux, the leading spaces are exclude when it is sorting.

```zsh
# Mac
$ a=(' a1' 'a0' ' b1' 'b0')
$ echo ${(o)a}
 a1  b1 a0 b0
```

```zsh
# Arch Linux
$ a=(' a1' 'a0' ' b1' 'b0')
$ echo ${(o)a}
a0  a1 b0  b1
```

**Comment by chitoku-k** [comment]
Then it's a locale problem. Thanks for investigating!
