### ISSUE TITLE
Support `env` and parameter assignment before command

### ISSUE THREAD

**Issue by hexium310** [chitoku-k/fzf-zsh-completions#138]
### Command name

env

### Completion context

```shell
# I know that the completion of git doesn't support GIT_DIR.
env GIT_EDITOR=vim GIT_DIR=/path/to git commit **<Tab>

# I know unimplemented, this is an example.
MANPAGER='nvim +Man!' man **<Tab>
```

### What happens now?

The completion of the command is shown while ignoring `env` and parameters.

### What do you expect to complete?

Suitable items for a command

**Comment by chitoku-k** [comment]
For parameter assignment, it looks like it’s already implemented in fzf. It might be our completion functions which breaks this mechanism...
https://github.com/junegunn/fzf/blob/0.27.2/shell/completion.zsh#L115

**Comment by hexium310** [comment]
There is `__fzf_extract_command`, which parsing parameters, but values passing to `_fzf_complete_<command>` are not the things excluding parameters from `$LBUFFER` but raw `$LBUFFER`. Thus, our functions don't break the mechanism.
https://github.com/junegunn/fzf/blob/e086f0b3fe1cb56df1335037cfd3d612defce082/shell/completion.zsh#L303

**Comment by hexium310** [comment]
I will be able to implement this utilizing `__fzf_extract_command`.
