### ISSUE TITLE
Propagation of preceding environment variables

### ISSUE THREAD

**Issue by chitoku-k** [chitoku-k/fzf-zsh-completions#198]
### Command name

(all)

### Completion context

```shell
CF_HOME=/tmp/foundation01 cf target -o **<TAB>
DOCKER_HOST=tcp://192.0.2.1:2375 docker start **<TAB>
GH_CONFIG_DIR=/tmp/gh gh pr view **<TAB>
GIT_DIR=/tmp/git git add **<TAB>
KUBECONFIG=/tmp/kube kubectl get **<TAB>
VAULT_ADDR=http://192.0.2.1:8200 vault list **<TAB>
```

### What happens now?

All preceding variables are ignored.

### What do you expect to complete?

Call the commands with all preceding variables when exist.

**Comment by hexium310** [comment]
Probably using the `local -x` command resolves it. https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html
