### ISSUE TITLE
Support glab auto completion

### ISSUE THREAD

**Issue by braineo** [chitoku-k/fzf-zsh-completions#245]
### Command name

glab

### Completion context

```shell
# glab is a cli client for gitlab just like gh for github

glab mr checkout **<TAB>
```

### What happens now?

Nothing happens

### What do you expect to complete?

I pretty much copy and modify the complete function for `gh` and put it in my config. I can open a pr if you want :)

https://github.com/braineo/configs/blob/master/zim/dot-fzf.zsh#L37

**Comment by chitoku-k** [comment]
Hi, feel free to open a PR for glab!
